version: '3.9'

services:

  back:
    container_name: "hacarus_back"
    build: ./python_backend
    volumes:
      - ./python_backend:/python_backend
    ports:
      - 8081:8081
      - 8888:8888
    # ホットリロードを有効化
    environment:
      - CHOKIDAR_USEPOLLING=true

  mysql:
    build: ./MySQL #Dockerfileからビルドすることを示す
    volumes:
      - ./mysql/DB:/docker-entrypoint-initdb.d #初期に実行するsql文を指定する
    image: test_mysql_hacarus # イメージの名前
    environment:
      - MYSQL_ROOT_PASSWORD=mypassword   #コンテナ内のMySQLを起動する際のパスワードを設定